name: Tafarel's Blog
description:
meta_description: "Tafarel's Blog"

# Site settings
title: Tafarel's Blog
email: jltafarel@gmail.com
description: "Nerd, programador e pseudo-músico."
url: "http://jltafarel.github.io/blog"
twitter_username: jltafarel
github_username:  jltafarel
facebook_username:  jltafarel

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
